### ISSUE TITLE
Multipart上传失败

### ISSUE THREAD

**Issue by Gongsc** [journeymidnight/yig#135]
使用s3cmd进行分段文件上传，在complete的时候报错
```
Unable to complete multipart upload.
With error:  Error 1292: Incorrect datetime value: '2019-07-08T07:20:18.000Z' for column `yig`.`objectpart`.`lastmodified` at row
```

**Comment by thesues** [comment]
What's your version of s3cmd?
Mine is 
```
$ s3cmd --version
s3cmd version 2.0.1+
```
it works for local test

**Comment by thesues** [comment]
we have a gitter to help the community.

https://gitter.im/journeymidnight

you can join us to discuss your issues.

**Comment by Gongsc** [comment]
My version is：
```
s3cmd --version
s3cmd version 2.0.2
```
I have tried version 2.0.1, but it returned the same error

**Comment by thesues** [comment]
it is a bug about when using mariadb as backend. Try to use Tidb instead,
