### ISSUE TITLE
yig配置问题

### ISSUE THREAD

**Issue by hyh012356789** [journeymidnight/yig#15]
这是我的yig配置，对其中的配置项有些疑惑。
aim是需要单独安装吗？
S3Domain该怎么设置呢？
现在想用s3cmd测试，不知道怎么配置？
{
    "S3Domain": "http://10.64.34.200:7480",
    "Region": "cn-bj-1",
    "IamEndpoint": "http://10.64.34.200:9006",
    "IamKey": "key",
    "IamSecret": "secret",
    "LogPath": "/var/log/yig/yig.log",
    "PanicLogPath":"/var/log/yig/panic.log",
    "PidFile": "/var/run/yig/yig.pid",
    "BindApiAddress": "10.64.34.200:80",
    "BindAdminAddress": "10.64.34.200:9000",
    "SSLKeyPath": "",
    "SSLCertPath": "",
    "ZookeeperAddress": "hbase:2181",
    "RedisAddress": "redis:6379",
    "RedisConnectionNumber": 10,
    "InMemoryCacheMaxEntryCount": 100000,
    "DebugMode": true,
    "AdminKey": "secret",
    "MetaCacheType": 0,
    "EnableDataCache": false,
    "CephConfigPattern": "/etc/ceph/ceph1.conf",
    "MetaStore": "tidb",
    "TidbInfo":"root:123456@tcp(127.0.0.1:3306)/yig?charset=utf8",
    "KeepAlive":true
}

**Comment by dahefanteng** [comment]
@hyh012356789  
aim是需要单独安装吗？
真实环境下，IAM需要单独安装，可以用来对接公司已有ldap等系统。测试用途下，将DebugMode配置为true时候，可以使用ak:hehehehe/sk:hehehehe来测试。
S3Domain该怎么设置呢？
一般而言，将S3Domain配置为域名，然后配置泛域名解析，将其解析到对应的IP上。
例如：
a，修改配置文件对应行为：  "S3Domain": "s3.test.com",
b,   安装dnsmasq：yum install dnsmasq -y;
      修改配置文件，增加一行address=/.s3.test.com/{你的IP}
      启动dnsmasq：systemctl start dnsmasq
c,  修改s3cmd所在机器，将dns服务器指向上一步骤配置的dnsmasq所在节点

**Comment by hyh012356789** [comment]
您好，感谢您的回复。
       我们现在的测试环境有ceph集群，上面想用yig，现在"DebugMode":设true，s3cmd中的endpoint是设置成"BindApiAddress": "10.64.34.200:7480"吗？
       我现在测试一直连不上。

**Comment by dahefanteng** [comment]
请问您可以贴一下详细信息吗？ 包括s3cmd的配置文件，yig配置文件，命令行报错信息和/var/log/yig/yig.log的相关日志

**Comment by dahefanteng** [comment]
s3domain应该使用域名，java代码部分也应该使用域名。java实现可以参考：https://github.com/journeymidnight/s3-sdk-samples/blob/master/java/S3Sample.java。

**Comment by hyh012356789** [comment]
能不能直接通过api的adress进行访问呢？感觉走域名解析这一步有点麻烦。

**Comment by dahefanteng** [comment]
使用域名访问属于S3协议的做法，这样可以支持将bucket放到域名中来进行相关操作，yig兼容S3协议，因此也使用域名来访问。
