### ISSUE TITLE
rados/conn.go:5:29: fatal error: rados/librados.h: No such file or directory

### ISSUE THREAD

**Issue by yilingyi** [journeymidnight/yig#89]
我在执行go get时提示找不到librados.h,请问该怎么处理？
[root@yig-185 yig]# go get ./...
# github.com/journeymidnight/yig/vendor/github.com/journeymidnight/radoshttpd/rados
vendor/github.com/journeymidnight/radoshttpd/rados/conn.go:5:29: fatal error: rados/librados.h: No such file or directory
 // #include <rados/librados.h>
                             ^
compilation terminated.

**Comment by cxt90730** [comment]
@yilingyi You need install package `ceph-devel` on Linux. If you wanna build and then run yig on Linux, you can read README.md. Otherwise you have to read integrate/README.md,   build and run yig in docker.

**Comment by e21407** [comment]
how to install package ceph-devel?

**Comment by tskdsb** [comment]
> how to install package ceph-devel?

https://github.com/ceph/go-ceph#installation
